#!/usr/bin/env python3
"""Generate storage identity-digest golden fixtures for the Java contract tests.

Read-only against the Python agentgate implementation: imports
storage/mysql.py::_digest/_target_key and records digests for single-part ids and
four-part TargetRef identities. The Python repo is never modified.

Usage:
    /path/to/pythonwork/agentgate/.venv/bin/python scripts/generate_identity_digests_golden.py \
        [--python-src /path/to/agentgate/src] [--output path.json]
"""

from __future__ import annotations

import argparse
import json
import platform
import sys
import uuid
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PYTHON_SRC = "/Users/eric/hw/xql/pythonwork/agentgate/src"
DEFAULT_OUTPUT = REPO_ROOT / "src/test/resources/contract/identity-digests.json"

SINGLE_PART_IDS: list[str] = [
    "run-1",
    "6f9619ff-8b86-d011-b42d-00c04fc964ff",
    "中文标识",
    "emoji-🚀-id",
    "with spaces and:colons",
    'quote"and\\backslash',
    "x" * 500,
    "",
]

TARGET_REFS: list[tuple[str, str, str, str]] = [
    ("demo", "agent", "loan", "v1"),
    ("行内平台", "skill", "技能-01", "版本-α"),
    ("demo", "agent", "loan", "v2"),
    ("src-x", "skill", "ext-y", "ver-z"),
]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--python-src", default=DEFAULT_PYTHON_SRC)
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    args = parser.parse_args()

    sys.path.insert(0, args.python_src)
    from agentgate.domain.target import TargetRef, TargetType
    from agentgate.storage.mysql import _digest, _target_key

    samples = []
    for value in SINGLE_PART_IDS:
        samples.append({
            "name": f"single_{len(samples):02d}",
            "parts": [value],
            "digest_hex": _digest(value).hex(),
        })

    for index, (source_id, target_type, external_id, external_version) in enumerate(TARGET_REFS):
        parts = [source_id, target_type, external_id, external_version]
        samples.append({
            "name": f"target_ref_{index:02d}",
            "parts": parts,
            "digest_hex": _digest(*parts).hex(),
        })

    ref_samples = []
    for index, (source_id, target_type, external_id, external_version) in enumerate(TARGET_REFS):
        ref = TargetRef(source_id=source_id, target_type=TargetType(target_type),
                        external_target_id=external_id, external_version_id=external_version)
        ref_samples.append({
            "name": f"target_key_{index:02d}",
            "parts": [source_id, target_type, external_id, external_version],
            "digest_hex": _target_key(ref).hex(),
        })

    document = {
        "description": (
            "Golden fixtures for storage identity digests (BINARY(32) keys) parity with "
            "Python agentgate.storage.mysql._digest. Generated by "
            "scripts/generate_identity_digests_golden.py."
        ),
        "python_version": platform.python_version(),
        "samples": samples,
        "target_key_samples": ref_samples,
    }

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, "w", encoding="utf-8") as handle:
        json.dump(document, handle, ensure_ascii=False, indent=2)
        handle.write("\n")
    print(f"wrote {len(samples)} digest samples and {len(ref_samples)} target-key samples "
          f"to {output}")


if __name__ == "__main__":
    main()
