#!/usr/bin/env python3
"""Generate ApiKeyMetadata golden fixtures for the Java domain contract tests.

Read-only against the Python agentgate implementation. The Python repo is never
modified.

Usage:
    /path/to/pythonwork/agentgate/.venv/bin/python scripts/generate_credentials_golden.py \
        [--python-src /path/to/agentgate/src] [--output path.json]
"""

from __future__ import annotations

import argparse
import json
import platform
import sys
from datetime import UTC, datetime, timedelta, timezone
from pathlib import Path

from pydantic import ValidationError

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PYTHON_SRC = "/Users/eric/hw/xql/pythonwork/agentgate/src"
DEFAULT_OUTPUT = REPO_ROOT / "src/test/resources/contract/credentials.json"

T0 = datetime(2026, 1, 1, tzinfo=UTC)
T1 = datetime(2026, 1, 2, tzinfo=UTC)
BEIJING = timezone(timedelta(hours=8))

LEGAL_SAMPLES: list[tuple[str, dict]] = [
    ("metadata_shared", {"id": "k1", "name": "主力密钥", "provider_id": "openai",
                         "scope": "shared", "created_at": T0, "updated_at": T0}),
    ("metadata_private", {"id": "k2", "name": "私有密钥", "provider_id": "anthropic",
                          "scope": "private", "created_at": T0, "updated_at": T1}),
    ("metadata_microseconds", {"id": "k3", "name": "微秒", "provider_id": "azure",
                               "scope": "shared",
                               "created_at": datetime(2026, 1, 1, 0, 0, 0, 1, tzinfo=UTC),
                               "updated_at": datetime(2026, 1, 2, 0, 0, 0, 123456, tzinfo=UTC)}),
    ("metadata_offset_normalized", {"id": "k4", "name": "时区归一", "provider_id": "local",
                                    "scope": "private",
                                    "created_at": datetime(2026, 1, 1, 8, 0, 0, tzinfo=BEIJING),
                                    "updated_at": datetime(2026, 1, 2, 8, 0, 0, tzinfo=BEIJING)}),
]

INVALID_SAMPLES: list[tuple[str, dict]] = [
    ("metadata_blank_id", {"id": " ", "name": "n", "provider_id": "p", "scope": "shared",
                           "created_at": T0, "updated_at": T0}),
    ("metadata_blank_name", {"id": "k", "name": " ", "provider_id": "p", "scope": "shared",
                             "created_at": T0, "updated_at": T0}),
    ("metadata_blank_provider", {"id": "k", "name": "n", "provider_id": " ", "scope": "shared",
                                 "created_at": T0, "updated_at": T0}),
    ("metadata_missing_scope", {"id": "k", "name": "n", "provider_id": "p",
                                "created_at": T0, "updated_at": T0}),
    ("metadata_bad_scope", {"id": "k", "name": "n", "provider_id": "p", "scope": "team",
                            "created_at": T0, "updated_at": T0}),
    ("metadata_updated_before_created", {"id": "k", "name": "n", "provider_id": "p",
                                         "scope": "shared",
                                         "created_at": T1, "updated_at": T0}),
    ("metadata_missing_name", {"id": "k", "provider_id": "p", "scope": "shared",
                               "created_at": T0, "updated_at": T0}),
]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--python-src", default=DEFAULT_PYTHON_SRC)
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    args = parser.parse_args()

    sys.path.insert(0, args.python_src)
    from agentgate.domain.base import canonical_json, content_sha256
    from agentgate.domain.credential import ApiKeyMetadata

    samples = []
    for name, value in LEGAL_SAMPLES:
        model = ApiKeyMetadata.model_validate(value)
        payload = model.model_dump(mode="json")
        samples.append({
            "name": name,
            "input": value,
            "payload": payload,
            "canonical": canonical_json(model),
            "sha256": content_sha256(model),
        })

    invalid = []
    for name, value in INVALID_SAMPLES:
        try:
            ApiKeyMetadata.model_validate(value)
        except ValidationError as exc:
            errors = exc.errors()
            assert errors, f"sample {name}: no validation errors"
            invalid.append({
                "name": name,
                "input": value,
                "error": errors[0]["msg"].removeprefix("Value error, "),
            })
        else:
            raise SystemExit(f"invalid sample {name} unexpectedly passed validation")

    document = {
        "description": (
            "Golden fixtures for ApiKeyMetadata parity with Python "
            "agentgate.domain.credential. Generated by "
            "scripts/generate_credentials_golden.py."
        ),
        "python_version": platform.python_version(),
        "samples": samples,
        "invalid_samples": invalid,
    }

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)

    def json_default(value: object) -> str:
        if isinstance(value, datetime):
            return value.isoformat()
        raise TypeError(f"not JSON serializable: {type(value).__name__}")

    with open(output, "w", encoding="utf-8") as handle:
        json.dump(document, handle, ensure_ascii=False, indent=2, default=json_default)
        handle.write("\n")
    print(f"wrote {len(samples)} legal samples and {len(invalid)} invalid samples to {output}")


if __name__ == "__main__":
    main()
