#!/usr/bin/env python3
"""Generate evaluator publication golden fixtures for the Java contract tests.

Read-only against the Python agentgate implementation: calls
evaluator/versioning.py::publish_evaluator_draft and records the assembled
EvaluatorSpec payloads. The Python repo is never modified.

Usage:
    /path/to/pythonwork/agentgate/.venv/bin/python scripts/generate_evaluator_publications_golden.py \
        [--python-src /path/to/agentgate/src] [--output path.json]
"""

from __future__ import annotations

import argparse
import json
import platform
import sys
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PYTHON_SRC = "/Users/eric/hw/xql/pythonwork/agentgate/src"
DEFAULT_OUTPUT = REPO_ROOT / "src/test/resources/contract/evaluator-publications.json"

T0 = datetime(2026, 1, 1, tzinfo=UTC)
T1 = datetime(2026, 1, 2, tzinfo=UTC)


def evaluator(**overrides: object) -> dict:
    value: dict[str, object] = {"id": "ev-1", "name": "状态评测器",
                                "created_at": T0, "updated_at": T0}
    value.update(overrides)
    return value


def draft(**overrides: object) -> dict:
    value: dict[str, object] = {
        "id": "draft-1", "evaluator_id": "ev-1", "kind": "rule",
        "dimension": "state", "metric": "state_metric", "severity": "standard",
        "implementation_id": "final_state", "implementation_version": "1",
        "created_at": T0, "updated_at": T1,
        "user_team_id": "team-1", "user_id": "u1", "user_name": "张三",
    }
    value.update(overrides)
    return value


LEGAL_SAMPLES: list[tuple[str, dict, dict, int]] = [
    ("publish_rule", evaluator(), draft(), 1),
    ("publish_version_large", evaluator(), draft(), 42),
    ("publish_hybrid", evaluator(), draft(
        kind="hybrid",
        children=[{"evaluator_id": "a", "evaluator_version": "1", "weight": 0.6},
                  {"evaluator_id": "b", "evaluator_version": "2", "weight": 0.4}],
        combination="weighted_score"), 3),
    ("publish_llm_judge", evaluator(), draft(
        kind="llm_judge", dimension="quality", metric="judge_score",
        implementation_id="llm_judge",
        config={"model": {"provider_id": "openai", "model_id": "gpt-4o"}}), 2),
    ("publish_blocking", evaluator(), draft(severity="blocking"), 5),
]

INVALID_SAMPLES: list[tuple[str, dict, dict, int]] = [
    ("publish_builtin_evaluator", evaluator(source="builtin", enabled=True), draft(), 1),
    ("publish_foreign_draft", evaluator(), draft(evaluator_id="ev-other"), 1),
    ("publish_zero_version", evaluator(), draft(), 0),
    ("publish_negative_version", evaluator(), draft(), -1),
]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--python-src", default=DEFAULT_PYTHON_SRC)
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    args = parser.parse_args()

    sys.path.insert(0, args.python_src)
    from agentgate.domain.base import canonical_json, content_sha256
    from agentgate.domain.evaluator import Evaluator, EvaluatorDraft
    from agentgate.evaluator.versioning import publish_evaluator_draft

    samples = []
    for name, evaluator_input, draft_input, version in LEGAL_SAMPLES:
        model = publish_evaluator_draft(
            Evaluator.model_validate(evaluator_input),
            EvaluatorDraft.model_validate(draft_input),
            version,
        )
        samples.append({
            "name": name,
            "evaluator": evaluator_input,
            "draft": draft_input,
            "version": version,
            "payload": model.model_dump(mode="json"),
            "canonical": canonical_json(model),
            "sha256": content_sha256(model),
        })

    invalid = []
    for name, evaluator_input, draft_input, version in INVALID_SAMPLES:
        try:
            publish_evaluator_draft(
                Evaluator.model_validate(evaluator_input),
                EvaluatorDraft.model_validate(draft_input),
                version,
            )
        except ValueError as exc:
            invalid.append({
                "name": name,
                "evaluator": evaluator_input,
                "draft": draft_input,
                "version": version,
                "error": str(exc),
            })
        else:
            raise SystemExit(f"invalid sample {name} unexpectedly passed")

    document = {
        "description": (
            "Golden fixtures for EvaluatorVersioning.publish parity with Python "
            "agentgate.evaluator.versioning.publish_evaluator_draft. Generated by "
            "scripts/generate_evaluator_publications_golden.py."
        ),
        "python_version": platform.python_version(),
        "samples": samples,
        "invalid_samples": invalid,
    }

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)

    def json_default(value: object) -> str:
        if isinstance(value, datetime):
            return value.isoformat()
        raise TypeError(f"not JSON serializable: {type(value).__name__}")

    with open(output, "w", encoding="utf-8") as handle:
        json.dump(document, handle, ensure_ascii=False, indent=2, default=json_default)
        handle.write("\n")
    print(f"wrote {len(samples)} legal samples and {len(invalid)} invalid samples to {output}")


if __name__ == "__main__":
    main()
