#!/usr/bin/env python3
"""Generate API Key encryption golden fixtures for the Java contract tests.

Read-only against the Python agentgate implementation: encrypts sample
plaintexts with integrations/credentials/encryption.py (fixed master key) and
records ciphertext pairs plus every sanitized failure path. The Python repo is
never modified.

Usage:
    /path/to/pythonwork/agentgate/.venv/bin/python scripts/generate_api_key_encryption_golden.py \
        [--python-src /path/to/agentgate/src] [--output path.json]
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import platform
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PYTHON_SRC = "/Users/eric/hw/xql/pythonwork/agentgate/src"
DEFAULT_OUTPUT = REPO_ROOT / "src/test/resources/contract/api-key-encryption.json"

PLAINTEXTS: list[tuple[str, str]] = [
    ("simple_ascii", "sk-abc123"),
    ("with_underscores", "AKIAIOSFODNN7EXAMPLE"),
    ("chinese", "密钥-测试-001"),
    ("spaces_inside", "key with spaces kept"),
    ("special_characters", "p@ss+ph/ase=42!"),
    ("long_key", "k" * 200),
    ("unicode_mixed", "混合-key-🚀"),
    ("single_char", "x"),
]

INVALID_MASTER_KEYS: list[tuple[str, bytes]] = [
    ("too_short", b"x" * 15),
    ("too_long", b"x" * 33),
]

INVALID_ENV_VALUES: list[tuple[str, str]] = [
    ("illegal_chars", "not base64!!"),
    ("standard_base64_plus", "+AB="),
    ("decoded_too_short", "AAAA"),
    ("empty_string", ""),
    ("whitespace_only", "   "),
]

DECRYPT_FAILURE = "encrypted API Key cannot be decrypted"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--python-src", default=DEFAULT_PYTHON_SRC)
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    args = parser.parse_args()

    sys.path.insert(0, args.python_src)
    from agentgate.integrations.credentials.encryption import (
        ApiKeyEncryptor,
    )

    master_key = hashlib.sha256(b"agentgate-golden-master").digest()
    encryptor = ApiKeyEncryptor(master_key)

    samples = []
    for name, plaintext in PLAINTEXTS:
        samples.append({
            "name": name,
            "plaintext": plaintext,
            "encrypted": encryptor.encrypt(plaintext),
        })

    reference = samples[0]["encrypted"]
    body = reference.removeprefix("v1.")
    invalid_ciphertexts = [
        {"name": "wrong_prefix", "encrypted": "v2." + body},
        {"name": "no_prefix", "encrypted": body},
        {"name": "trailing_padding", "encrypted": reference + "="},
        {"name": "non_urlsafe_chars", "encrypted": "v1." + body.replace(body[0], "+", 1)},
        {"name": "too_short_payload", "encrypted": "v1." + "AAAA"},
        {"name": "tampered_byte", "encrypted": "v1." + body[:6] + ("A" if body[6] != "A" else "B") + body[7:]},
        {"name": "random_bytes", "encrypted": "v1." + base64.urlsafe_b64encode(b"junk-junk-junk").rstrip(b"=").decode()},
    ]
    for item in invalid_ciphertexts:
        try:
            encryptor.decrypt(item["encrypted"])
        except ValueError as exc:
            item["error"] = str(exc)
            assert item["error"] == DECRYPT_FAILURE, item
        else:
            raise SystemExit(f"invalid ciphertext {item['name']} unexpectedly decrypted")

    invalid_master_key_samples = []
    for name, key in INVALID_MASTER_KEYS:
        try:
            ApiKeyEncryptor(key)
        except ValueError as exc:
            invalid_master_key_samples.append({
                "name": name, "key_hex": key.hex(), "error": str(exc),
            })
        else:
            raise SystemExit(f"invalid master key {name} unexpectedly accepted")

    blank_plaintext_error = None
    for plaintext in ("", "   "):
        try:
            encryptor.encrypt(plaintext)
        except ValueError as exc:
            blank_plaintext_error = str(exc)
    assert blank_plaintext_error == "API Key plaintext must be a nonblank string"

    invalid_env_samples = []
    for name, value in INVALID_ENV_VALUES:
        try:
            from agentgate.integrations.credentials.environment import _decode_master_key
            _decode_master_key(value)
        except ValueError as exc:
            invalid_env_samples.append({"name": name, "value": value, "error": str(exc)})
        else:
            raise SystemExit(f"invalid env value {name} unexpectedly accepted")

    document = {
        "description": (
            "Golden fixtures for ApiKeyEncryptor parity with Python "
            "agentgate.integrations.credentials. Nonce is random so ciphertexts "
            "differ per run; regenerate to refresh. Generated by "
            "scripts/generate_api_key_encryption_golden.py."
        ),
        "python_version": platform.python_version(),
        "master_key_hex": master_key.hex(),
        "samples": samples,
        "invalid_ciphertexts": invalid_ciphertexts,
        "invalid_master_keys": invalid_master_key_samples,
        "invalid_env_values": invalid_env_samples,
        "blank_plaintext_error": blank_plaintext_error,
    }

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, "w", encoding="utf-8") as handle:
        json.dump(document, handle, ensure_ascii=False, indent=2)
        handle.write("\n")
    print(f"wrote {len(samples)} pairs, {len(invalid_ciphertexts)} invalid ciphertexts, "
          f"{len(invalid_master_key_samples)} invalid keys, "
          f"{len(invalid_env_samples)} invalid env values to {output}")


if __name__ == "__main__":
    main()
